name: Natural Life Clinic
favicon: null
layout_spectrum: 0.8195615
typography_spectrum: 0.336658142041415
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2dd11'
    - '#007a09'
    - '#a3cfa7'
    - '#4ba04f'
  brandStrength: 1
  lightness: 0.3735245
  saturation: 1
  rhythmicContrast: 0.9595279
purpose: []
