layout_spectrum: 0.8679167260415852
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6971939241047949
  lightness: 0.3653868671972305
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#017F3B'
    - '#A6CD38'
    - '#96C7AA'
    - '#D8E9AD'
  rhythmicContrast: 0.842523256316781
typography_spectrum: 0.336658142041415
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Natural Life Clinic
