name: Natural Life Clinic
favicon: null
layout_spectrum: 0.8679167260415852
typography_spectrum: 0.336658142041415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9326516818255186
  lightness: 0.36538686719723046
  saturation: 0.6971939241047949
  rhythmicContrast: 0.842523256316781
purpose: []
